pipeline {
    agent {
      docker { image 'node:14-alpine' }
    }
    stages {
      stage('clone') {
        steps {
          git branch: 'master'
        }
      }
      stage('build') {
        steps {
          sh 'node -v'
          sh 'npm install'
        }
      }
      stage('unit tests') {
        steps {
          sh 'npm test'
        }
      }
    }
}