pipeline {
    agent {
      docker { image 'node:14-alpine' }
      environment {
        HOME = '.'
      }
    }
    stages {
      stage('build') {
          steps {
              sh 'node -v'
              // sh 'chown -R 117:123 "/.npm"'
              sh 'npm install'
          }
      }
    }
}