pipeline {
  agent {
    node { label 'master' }
  }
  stages {
    stage('install') {
      steps {
        sh 'node -v'
        sh 'echo $PWD'
        sh 'npm install'
      }
    }
    stage('unit tests') {
      steps {
        sh 'npm run test:ci'
      }
    }
    stage('build') {
      steps {
        sh 'npm run build'
      }
    }
    stage('deploy') {
      steps {
        sh 'rm -rf /home/pi/public_html/*'
        sh 'cp -R ${PWD}/build/* /home/pi/public_html/'
        // sh 'docker run -it --rm -d -p $CLIENT_PORT:$PORT --name my_content_client \
        //     -v $PWD/nginx/conf.d:/etc/nginx/conf.d \
        //     -v $PWD/build:/usr/share/nginx/html nginx'
      }
    }
  }
}
